version: "3.9"

services:
  redis:
      image: redis:7
      ports:
        - "6379:6379"
  celery:
    build:
      context: ./backend
    command: celery -A app.celery_app worker --loglevel=info
    working_dir: /app
    volumes:
      - ./backend:/app
    depends_on:
      - backend
      - redis

  beat:
    build:
      context: ./backend
    command: celery -A app.celery_app beat --loglevel=info
    working_dir: /app
    volumes:
      - ./backend:/app
    depends_on:
      - backend
      - redis

  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: zapier_genai_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/zapier_genai_db


  frontend:
    build:
      context: ./frontend/zapier_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/zapier_frontend:/app
      - /app/node_modules
    working_dir: /app
    environment:
      - NODE_ENV=development




volumes:
  postgres_data:
